# Esportatori per database e servizi

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://nearuser:nearypass@postgres-postgis:5432/near_you_shops?sslmode=disable"
    ports:
      - "9187:9187"
    restart: unless-stopped
    depends_on:
      - postgres-postgis
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9187/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    environment:
      - REDIS_ADDR=redis-cache:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "9121:9121"
    restart: unless-stopped
    depends_on:
      - redis-cache
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9121/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  clickhouse-exporter:
    image: f1yegor/clickhouse-exporter
    container_name: clickhouse-exporter
    environment:
      - CLICKHOUSE_URL=http://clickhouse-server:8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    ports:
      - "9116:9116"
    restart: unless-stopped
    depends_on:
      - clickhouse-server
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9116/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  kafka-exporter:
    image: danielqsj/kafka-exporter
    container_name: kafka-exporter
    command:
      - --kafka.server=kafka:9093
      - --tls.enabled=true
      - --tls.ca-file=/etc/kafka/certs/ca.crt
      - --tls.cert-file=/etc/kafka/certs/client_cert.pem
      - --tls.key-file=/etc/kafka/certs/client_key.pem
    volumes:
      - ./certs:/etc/kafka/certs:ro
    ports:
      - "9308:9308"
    restart: unless-stopped
    depends_on:
      - kafka
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9308/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3

  airflow-exporter:
    image: pbweb/airflow-prometheus-exporter
    container_name: airflow-exporter
    environment:
      - AIRFLOW_PROMETHEUS_DEBUG=false
      - AIRFLOW_URL=http://nearyou-airflow-webserver-1:8080
      - AIRFLOW_USER=admin
      - AIRFLOW_PASSWORD=admin
    ports:
      - "9112:9112"
    restart: unless-stopped
    depends_on:
      - nearyou-airflow-webserver-1
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9112/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3