name: NearYou CD Production

# Attivazione del workflow
on:
  push:
    branches: [ main ]      # Attiva su push al branch main
    tags: [ 'v*' ]          # Attiva su tag di versione
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Conferma deployment in produzione'
        required: true
        type: boolean
        default: false

jobs:
  deploy-production:
    name: Deploy in Produzione
    runs-on: ubuntu-latest
    environment: production
    # Solo tag o conferma manuale
    if: startsWith(github.ref, 'refs/tags/v') || github.event.inputs.confirm_deploy == 'true'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Configura credenziali AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          
      - name: Login ad Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Configura Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Cache layer Docker
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Estrai metadati (tag, etichette)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/nearyou
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short
            latest
      
      - name: Build e push immagine Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deployment/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          
      # Sposta cache
      - name: Sposta cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      
      - name: Configura Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "4.5.7"
      
      - name: Aggiorna risorse Kubernetes
        run: |
          cd deployment/k8s/overlays/prod
          kustomize edit set image nearyou=${{ steps.meta.outputs.tags }}
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Aggiorna immagine produzione a ${{ github.sha }}" || echo "Nessuna modifica da committare"
          git push
      
      # Richiede approvazione manuale prima di procedere
      - name: Approvazione manuale
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: ${{ vars.PRODUCTION_APPROVERS }}
          minimum-approvals: 1
          issue-title: "Deploy in Produzione"
          issue-body: "Si prega di approvare o rifiutare il deployment in produzione"
          exclude-workflow-initiator-as-approver: false
          
      - name: Deploy su Kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_PRODUCTION }}
        with:
          args: apply -k deployment/k8s/overlays/prod
          
      - name: Verifica deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_PRODUCTION }}
        with:
          args: rollout status deployment/nearyou -n nearyou-production
          
      - name: Crea Release GitHub
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          
      - name: Notifica deployment
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          notification_title: 'Deployment in produzione di {workflow} ha {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}> - Versione: ${{ github.ref_name }}'
          footer: '<{run_url}|Visualizza Esecuzione>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_PRODUCTION }}