FROM python:3.10-slim

WORKDIR /app

# Copia requirements e installa
COPY requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt

# Configura PYTHONPATH
ENV PYTHONPATH=/app/src

# Avvia il servizio
CMD ["uvicorn", "services.dashboard.main_user:app", "--host", "0.0.0.0", "--port", "8003", "--reload"]